# Generated by Django 5.2.8 on 2026-02-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='Εμφανίζεται στον χρήστη μετά την απάντηση (π.χ. γιατί είναι σωστό/λάθος)', null=True),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='is_unlocked',
            field=models.BooleanField(default=False),
        ),
    ]
