# Generated by Django 5.2.8 on 2026-02-21 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_question_explanation_studentprogress_is_unlocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='learning_style',
            field=models.CharField(default='visual', max_length=20),
        ),
    ]
