# Generated by Django 5.2.8 on 2026-02-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0005_usermistake'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='remedial_resource',
            field=models.URLField(blank=True, help_text='Link θεωρίας για διάβασμα', null=True),
        ),
    ]
