# Generated by Django 5.2.8 on 2026-02-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0006_question_remedial_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='video_resource',
            field=models.URLField(blank=True, help_text='Link για βίντεο αν ο χρήστης είναι οπτικός τύπος', null=True),
        ),
    ]
